language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "15"
  # - "15.1" #windows error on 15.0.0 invalid version
  - "14"
  - "14.14"
  - "14.1"
  - "12"
  - "12.12"
  - "12.0.0"
  - "11"
  - "11.0.0"
  - "10"
  - "10.13"
  # - "10.0.0"
  # - "9.11" # temporary disable older version in CI
  # - "8.12"
  # - "7.10"
  # - "6.14"
  # - "5.12"
  # - "4.9"
  # - "0.12"
  # - "0.11"
  # - "0.10"
  # - "iojs"

before_install:
  - node -v
  - npm i -g yarn
  - node install-correct-pnpm-version.js
  - yarn -v
  - pnpm -v

cache:
  directories:
    - "node_modules"

env:
  - YARN_GPG=no
