language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "11.1"
  - "10.12"
  - "9.11"
  - "8.12"
  # - "7.10" # temporary disable older version in CI
  # - "6.14"
  # - "5.12"
  # - "4.9"
  # - "0.12"
  # - "0.11"
  # - "0.10"
  # - "iojs"

before_install:
  - npm i -g yarn
  - npm i -g bower

cache:
  directories:
    - "node_modules"

env:
  - YARN_GPG=no
