name: Continuous Integration Linux

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [
            # 10.13,
            # 10.x,

            11.0.0,
            11.x,

            12.0.0,
            12.12.x,
            12.x,

            14.1.x,
            14.14.x,
            14.x,

            15.0.0,
            15.x,

            16.0.0,
            16.x,

            17.0.0,
            17.x,

            18.0.0,
            18.x,
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: npm -v

      - run: node install-correct-pnpm-version.js

      - run: yarn -v
      - run: pnpm -v

      # TODO
      # we need to remove global test
      - run: rm tests/global.test.ts

      # we need to remove parcel before install dependencies
      - run: rm package-lock.json
      - run: npm uninstall parcel

      # install dependencies without parcel
      - run: npm install
      - run: npm run ci:test
